# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yann/Projects/gtk/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yann/Projects/gtk/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yann/Projects/gtk/test/CMakeFiles /Users/yann/Projects/gtk/test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yann/Projects/gtk/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameOfLife

# Build rule for target.
GameOfLife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLife
.PHONY : GameOfLife

# fast build rule for target.
GameOfLife/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/build
.PHONY : GameOfLife/fast

core/buttons.o: core/buttons.c.o
.PHONY : core/buttons.o

# target to build an object file
core/buttons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/core/buttons.c.o
.PHONY : core/buttons.c.o

core/buttons.i: core/buttons.c.i
.PHONY : core/buttons.i

# target to preprocess a source file
core/buttons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/core/buttons.c.i
.PHONY : core/buttons.c.i

core/buttons.s: core/buttons.c.s
.PHONY : core/buttons.s

# target to generate assembly for a file
core/buttons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/core/buttons.c.s
.PHONY : core/buttons.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.s
.PHONY : main.c.s

src/frontend/application.o: src/frontend/application.c.o
.PHONY : src/frontend/application.o

# target to build an object file
src/frontend/application.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/application.c.o
.PHONY : src/frontend/application.c.o

src/frontend/application.i: src/frontend/application.c.i
.PHONY : src/frontend/application.i

# target to preprocess a source file
src/frontend/application.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/application.c.i
.PHONY : src/frontend/application.c.i

src/frontend/application.s: src/frontend/application.c.s
.PHONY : src/frontend/application.s

# target to generate assembly for a file
src/frontend/application.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/application.c.s
.PHONY : src/frontend/application.c.s

src/frontend/button_bar.o: src/frontend/button_bar.c.o
.PHONY : src/frontend/button_bar.o

# target to build an object file
src/frontend/button_bar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_bar.c.o
.PHONY : src/frontend/button_bar.c.o

src/frontend/button_bar.i: src/frontend/button_bar.c.i
.PHONY : src/frontend/button_bar.i

# target to preprocess a source file
src/frontend/button_bar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_bar.c.i
.PHONY : src/frontend/button_bar.c.i

src/frontend/button_bar.s: src/frontend/button_bar.c.s
.PHONY : src/frontend/button_bar.s

# target to generate assembly for a file
src/frontend/button_bar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_bar.c.s
.PHONY : src/frontend/button_bar.c.s

src/frontend/button_callbacks.o: src/frontend/button_callbacks.c.o
.PHONY : src/frontend/button_callbacks.o

# target to build an object file
src/frontend/button_callbacks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_callbacks.c.o
.PHONY : src/frontend/button_callbacks.c.o

src/frontend/button_callbacks.i: src/frontend/button_callbacks.c.i
.PHONY : src/frontend/button_callbacks.i

# target to preprocess a source file
src/frontend/button_callbacks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_callbacks.c.i
.PHONY : src/frontend/button_callbacks.c.i

src/frontend/button_callbacks.s: src/frontend/button_callbacks.c.s
.PHONY : src/frontend/button_callbacks.s

# target to generate assembly for a file
src/frontend/button_callbacks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/button_callbacks.c.s
.PHONY : src/frontend/button_callbacks.c.s

src/frontend/main_window.o: src/frontend/main_window.c.o
.PHONY : src/frontend/main_window.o

# target to build an object file
src/frontend/main_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/main_window.c.o
.PHONY : src/frontend/main_window.c.o

src/frontend/main_window.i: src/frontend/main_window.c.i
.PHONY : src/frontend/main_window.i

# target to preprocess a source file
src/frontend/main_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/main_window.c.i
.PHONY : src/frontend/main_window.c.i

src/frontend/main_window.s: src/frontend/main_window.c.s
.PHONY : src/frontend/main_window.s

# target to generate assembly for a file
src/frontend/main_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/src/frontend/main_window.c.s
.PHONY : src/frontend/main_window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameOfLife"
	@echo "... core/buttons.o"
	@echo "... core/buttons.i"
	@echo "... core/buttons.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/frontend/application.o"
	@echo "... src/frontend/application.i"
	@echo "... src/frontend/application.s"
	@echo "... src/frontend/button_bar.o"
	@echo "... src/frontend/button_bar.i"
	@echo "... src/frontend/button_bar.s"
	@echo "... src/frontend/button_callbacks.o"
	@echo "... src/frontend/button_callbacks.i"
	@echo "... src/frontend/button_callbacks.s"
	@echo "... src/frontend/main_window.o"
	@echo "... src/frontend/main_window.i"
	@echo "... src/frontend/main_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

